# Generated by Django 4.2.7 on 2024-01-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_tutorprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='teacher_certificates/')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tutorprofile')),
            ],
        ),
    ]
