# Generated by Django 4.2.7 on 2024-01-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentprofile_qualification'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='teacher_certificates/')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tutorprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherCertificate',
        ),
    ]
