# Generated by Django 4.2.7 on 2023-12-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_opened', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('register', 'register'), ('course', 'course'), ('video', 'video')], default='register', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('key', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
