# Generated by Django 4.2.7 on 2024-01-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_price'),
        ('notifications', '0003_remove_adminnotifications_course_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='tutor',
        ),
        migrations.AddField(
            model_name='notifications',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
