# Generated by Django 4.2.7 on 2023-12-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
