# Generated by Django 4.2.7 on 2023-12-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_profile',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
