# Generated by Django 4.2.7 on 2023-12-28 06:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
    ]
