# Generated by Django 4.2.7 on 2024-01-02 09:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_studentprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='tutor_profiles/'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='qualification',
            field=models.CharField(default='', max_length=100),
        ),
    ]
