# Generated by Django 4.2.7 on 2024-01-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_tutorprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='qualification',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
