# Generated by Django 4.2.7 on 2024-01-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_studentprofile_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_profile',
        ),
    ]
