# Generated by Django 4.2.7 on 2024-01-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(),
        ),
    ]
