# Generated by Django 4.2.7 on 2024-01-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_coursecategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
