# Generated by Django 4.2.7 on 2024-01-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
