# Generated by Django 4.2.7 on 2024-01-22 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideosCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField()),
                ('video_description', models.TextField()),
                ('is_available', models.BooleanField(default=False)),
                ('is_free_of_charge', models.BooleanField(default=False)),
                ('thumbnail_image', models.FileField(upload_to='video_thumbnails/')),
                ('video', models.FileField(upload_to='course_videos/')),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
