# Generated by Django 5.0.1 on 2024-01-31 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_videoscourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoscourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_video', to='course.course'),
        ),
    ]
