# Generated by Django 4.2.7 on 2024-02-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_coursepurchase_delete_purchasecourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepurchase',
            name='is_purchased',
        ),
    ]
