# Generated by Django 4.2.7 on 2024-02-14 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_coursereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='review',
            new_name='rating',
        ),
    ]
