# Generated by Django 4.2.7 on 2024-02-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
