# Generated by Django 4.2.7 on 2024-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_course_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='comment',
        ),
        migrations.AddField(
            model_name='videoscourse',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
